# å°†é™æ€å†…å®¹éƒ¨ç½²åˆ° GitHub Pages çš„ç®€å•å·¥ä½œæµ
name: å°†é™æ€å†…å®¹éƒ¨ç½²åˆ°é¡µé¢

on:
  # é’ˆå¯¹é»˜è®¤åˆ†æ”¯çš„æ¨é€ä¸Šè¿è¡Œ
  push:
    branches: ["master"]

  # å…è®¸æ‚¨ä»æ“ä½œé€‰é¡¹å¡æ‰‹åŠ¨è¿è¡Œæ­¤å·¥ä½œæµ
  workflow_dispatch:

# è®¾ç½® GITHUB_TOKEN æƒé™ä»¥å…è®¸éƒ¨ç½²åˆ° GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# å…è®¸ä¸€ä¸ªå¹¶è¡Œéƒ¨ç½²
concurrency:
  group: "é¡µé¢"
  cancel-in-progress: true

jobs:
  # ç”±äºæˆ‘ä»¬åªæ˜¯éƒ¨ç½²ï¼Œå› æ­¤å•ä¸ªéƒ¨ç½²ä½œä¸š
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: è®¾ç½® Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.com/
          # cache: "npm"
          # cache-dependency-path: "./"
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Deploy ğŸ”§
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: è®¾ç½®é¡µé¢
        uses: actions/configure-pages@v3
      - name: ä¸Šä¼ æ„ä»¶
        uses: actions/upload-pages-artifact@v1
        with:
          # ä¸Šä¼  dist åº“
          path: "./dist"
      - name: éƒ¨ç½²åˆ° GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
